import { Math } from '@vicons/tabler';
import { defineTool } from '../tool';

export const tool = defineTool({
  name: 'Math evaluator',
  path: '/math-evaluator',
  description: 'Một máy tính để đánh giá các biểu thức toán học. Bạn có thể sử dụng các hàm như sqrt, cos, sin, abs, v.v.',
  keywords: [
    'math',
    'evaluator',
    'calculator',
    'expression',
    'abs',
    'acos',
    'acosh',
    'acot',
    'acoth',
    'acsc',
    'acsch',
    'asec',
    'asech',
    'asin',
    'asinh',
    'atan',
    'atan2',
    'atanh',
    'cos',
    'cosh',
    'cot',
    'coth',
    'csc',
    'csch',
    'sec',
    'sech',
    'sin',
    'sinh',
    'sqrt',
    'tan',
    'tanh',
  ],
  component: () => import('./math-evaluator.vue'),
  icon: Math,
});
